//
//  DataManager.swift
//  SwiftTest
//
//  Created by Kuat Bodikov on 08.01.2022.
//

import Foundation

class DataManager {
    
    static let shared = DataManager()
    var quizes =
    Quizes(sections: [Sections(sections: "Основы Swift", rows: [Rows(rows: "Синтаксис Swift", questions:
                           [Questions(question: "Можем ли мы менять значение переменных?",
                                      optionA: "A. Ну да, но вообще-то нет",
                                      optionB: "B. Нет",
                                      optionC: "С. Да",
                                      optionD: "D. Зависит от обстоятельств",
                                      correctAnswer: 3),
                            Questions(question: "Если мы уверены, что значение свойства меняться не будет, что нужно использовать?",
                                      optionA: "A. Константу",
                                      optionB: "B. Литерал",
                                      optionC: "C. Переменную",
                                      optionD: "D. Свойство",
                                      correctAnswer: 1),
                            Questions(question: "Какая из перечисленных ниже строк создаст новую переменную?",
                                      optionA: "A. var name = «Tim Cook»",
                                      optionB: "B. fruit = «Apple»",
                                      optionC: "C. pet = «Rex»",
                                      optionD: "D. let city = «Moscow»",
                                      correctAnswer: 1),
                            Questions(question: "С какой буквы надо писать все типы в Swift?",
                                      optionA: "A. Со строчной буквы" ,
                                      optionB: "B. С заглавной буквы" ,
                                      optionC: "C. На свое усмотрение" ,
                                      optionD: "D. Это числовые значения, обмануть меня решили?",
                                      correctAnswer: 1),
                            Questions(
                                    question: "Можно ли присвоить значению свойство по умолчанию?",
                                    optionA: "A. Да" ,
                                    optionB: "B. Нет" ,
                                    optionC: "" ,
                                    optionD: "",
                                    correctAnswer: 1),
                            Questions(question: "С какой буквы должны именоваться свойства в Swift?",
                                      optionA: "A. По желанию" ,
                                      optionB: "B. Со второй буквы, первая не нужна" ,
                                      optionC: "C. С заглавной" ,
                                      optionD: "D. Со строчной",
                                      correctAnswer: 4),
                            Questions(question: "Любые целые числа без дробной части хранятся в типе:",
                                      optionA: "A. Float",
                                      optionB: "B. Int",
                                      optionC: "C. Trouble",
                                      optionD: "D. Double",
                                      correctAnswer: 2),
                            Questions(question: "Тип данных, отвечающий за хранение произвольной текстовой информации:",
                                      optionA: "A. Bool",
                                      optionB: "B. Int",
                                      optionC: "C. Character",
                                      optionD: "D. String",
                                      correctAnswer: 4),
                            Questions(question: "Каким ключевым словом можно определить константу?",
                                      optionA: "A. cat",
                                      optionB: "B. let",
                                      optionC: "C. set",
                                      optionD: "D. var",
                                      correctAnswer: 2),
                            Questions(question: "Какая из перечисленных ниже строк создаст целочисленное значение?",
                                      optionA: "A. var age = 40",
                                      optionB: "B. let power = «1000»",
                                      optionC: "C. var size = «12»",
                                      optionD: "D. var voltage = 220.0",
                                      correctAnswer: 1)
                           ]),
                   Rows(rows: "Базовые операторы",
                        questions: [
                            Questions(question: "Как называется оператор в этом выражении: a += 2?",
                                      optionA: "A. Присваивания",
                                      optionB: "B. Составного сложения",
                                      optionC: "С. Сложения",
                                      optionD: "D. Присваивания со сложением",
                                      correctAnswer: 3),
                            Questions(question: "Если при использовании логического И (&&) первый операнд = false,будет ли проверяться второе       выражение?",
                                      optionA: "A. Да",
                                      optionB: "B. Нет",
                                      optionC: "C. Переменную",
                                      optionD: "D. Свойство",
                                      correctAnswer: 2),
                            Questions(question: "Какой будет результат выражения 9 % 5 ?",
                                      optionA: "A. 1",
                                      optionB: "B. 3",
                                      optionC: "C. 6",
                                      optionD: "D. 4",
                                      correctAnswer: 4),
                            Questions(question: "Левая часть выражения с логическим оператором || равна true, будем ли мы проверять вторую часть?",
                                      optionA: "A. Зависит от операндов" ,
                                      optionB: "B. Нет" ,
                                      optionC: "C. Да, только если она true" ,
                                      optionD: "D. а, только если она false",
                                      correctAnswer: 2),
                            Questions(question: "Операторы, которые применяются к двум величинам",
                                      optionA: "A. Бинарные" ,
                                      optionB: "B. Тернарные" ,
                                      optionC: "C. Унарные" ,
                                      optionD: "D. Двоичные",
                                      correctAnswer: 1),
                            Questions(question: "Этот логический оператор будет давать true, когда хотя бы один операнд = true",
                                      optionA: "A. Логическое ИЛИ ||",
                                      optionB: "B. Логическое НЕ !",
                                      optionC: "C. Логическое И &&",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Присваивание объявленному объекту начального значения это:",
                                      optionA: "A. Объявление",
                                      optionB: "B. Инициализация",
                                      optionC: "C. Обновление",
                                      optionD: "D. Возведение",
//                                      optionE: "E. Присвоение",
                                      correctAnswer: 2),
                            Questions(question: "ТОЛЬКО когда оба операнда равны true, этот логический оператор дает true",
                                      optionA: "A. !",
                                      optionB: "B. ||",
                                      optionC: "C. &&",
                                      optionD: "D. ??",
//                                      optionE: "E. < >",
                                      correctAnswer: 3),
                            Questions(question: "Задайте диапазон от a до b, исключая b",
                                      optionA: "A. a..< b",
                                      optionB: "B. a..<",
                                      optionC: "C. …a",
                                      optionD: "D. a...< b",
//                                      optionE: "E. a...b",
//                                      optionE: "F. a...",
                                      correctAnswer: 1),
                            Questions(question: "Унарные операторы, которые ставятся перед величиной",
                                      optionA: "A. Постфиксные",
                                      optionB: "B. Суффиксные",
                                      optionC: "C. Префиксные",
                                      optionD: "",
//                                      optionE: "E. a...b",
//                                      optionE: "F. a...",
                                      correctAnswer: 3)
                        ]),
                   Rows(rows: "Условные инструкции",
                        questions:[
                            Questions(question: "Можно ли объявить опциональную константу без указания типа, например: let bikeVelocity = nil",
                                      optionA: "A. Нет",
                                      optionB: "B. Нет, объявлять таким образом можно только переменные",
                                      optionC: "C. Да",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Если оператор управления break выполняется внутри switch, что произойдет дальше?",
                                      optionA: "A. Завершается работа switch",
                                      optionB: "B. Начать сравнение сначала",
                                      optionC: "C. Переход к следующему кейсу",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Внутри инструкции switch можно использовать составные кейсы. Чем разделять их значения?",
                                      optionA: "A. Тире",
                                      optionB: "B. Логический оператор И &&",
                                      optionC: "C. Логический оператор ИЛИ ||",
                                      optionD: "D. Запятая",
                                      correctAnswer: 4),
                            Questions(question: "Внутри каждого случая switch - case обязательно должно содержаться это:",
                                      optionA: "A. Условие",
                                      optionB: "B. Сравнение",
                                      optionC: "C. Исполняемое выражение",
                                      optionD: "D. break",
                                      correctAnswer: 3),
                            Questions(question: "Будут ли проверяться все оставшиеся кейсы внутри инструкции switch, если уже было найдено совпадение?",
                                      optionA: "A. Да",
                                      optionB: "B. Нет",
                                      optionC: "C. Будет проверяться default",
                                      optionD: "",
                                      correctAnswer: 2),
                            Questions(question: "Как называется это выражение: let name = username!",
                                      optionA: "A. Насильственное извлечение опционала",
                                      optionB: "B. Извлечение опционала по принуждению",
                                      optionC: "C. Принудительное извлечение опционала",
                                      optionD: "",
                                      correctAnswer: 3),
                            Questions(question: "Если оператор управления fallthrough выполняется внутри switch, что произойдет дальше?",
                                      optionA: "A. Завершается работа switch",
                                      optionB: "B. Начать сравнение сначала",
                                      optionC: "C. Переход к следующему кейсу",
                                      optionD: "",
                                      correctAnswer: 3),
                            Questions(question: "В каком случае будет выполняться тело инструкции if?",
                                      optionA: "A. В любом случае",
                                      optionB: "B. Если условие возвращает true",
                                      optionC: "C. Если условие возвращает false",
                                      optionD: "D. Если задано условие",
                                      correctAnswer: 2),
                            Questions(question: "К чему приводит принудительное извлечение, когда опционала имеет nil?",
                                      optionA: "A. К извлечению значения",
                                      optionB: "B. Получим nil",
                                      optionC: "C. runtime ошибка",
                                      optionD: "",
                                      correctAnswer: 3),
                            Questions(question: "Как называется дополнительная ветка инструкции if?",
                                      optionA: "A. another",
                                      optionB: "B. repeat",
                                      optionC: "C. also",
                                      optionD: "D. else",
                                      correctAnswer: 4),
                        ]),
                   Rows(rows: "Типы коллекций",
                        questions:[
                            Questions(question: "Упорядоченная коллекция значений:",
                                      optionA: "A. Множество (Set)",
                                      optionB: "B. Словарь (Dictionary)",
                                      optionC: "C. Массив (Array)",
                                      optionD: "",
                                      correctAnswer: 3),
                            Questions(question: "Можем ли мы создавать вложенные циклы?",
                                      optionA: "A. Да",
                                      optionB: "B. Нет",
                                      optionC: "",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "В каком случае первая итерация цикла repeat-while приступит к исполнению?",
                                      optionA: "A. Условие цикла истинно",
                                      optionB: "B. В любом случае",
                                      optionC: "C. Условие цикла ложно",
                                      optionD: "",
                                      correctAnswer: 2),
                            Questions(question: "В каком из вариантов правильно инициализируются пустой массив?",
                                      optionA: "A. var array: [String]?",
                                      optionB: "B. var array = (String) []",
                                      optionC: "C. var array = [String()]",
                                      optionD: "D. var array: [String] = []",
//                                          optionE: "E. C. var array = [String] ()",
                                      correctAnswer: 4),
                            Questions(question: "В каком случае первая итерация цикла while приступит к исполнению?",
                                      optionA: "A. Условие цикла истинно",
                                      optionB: "B. Условие цикла ложно",
                                      optionC: "C. Первый раз цикл выполняется в любом случае",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Коллекция, хранящая неупорядоченные пары ключ-значение",
                                      optionA: "A. Множество (Set)",
                                      optionB: "B. Словарь (Dictionary)",
                                      optionC: "C. Массив (Array)",
                                      optionD: "D. Цикл (Loop)",
                                      correctAnswer: 2),
                            Questions(question: "Уникальные значения, собранные в неупорядоченную коллекцию",
                                      optionA: "A. Массив",
                                      optionB: "B. Словарь",
                                      optionC: "C. Множество",
                                      optionD: "",
                                      correctAnswer: 3),
                            Questions(question: "Какой тип коллекции использовать, чтобы ее значения не повторялись?",
                                      optionA: "A. Множество (Set)",
                                      optionB: "B. Массив (Array)",
                                      optionC: "C. Цикл (Loop)",
                                      optionD: "D. Словарь (Dictionary)",
                                      correctAnswer: 1),
                            Questions(question: "Какой метод нужно вызвать, чтобы вставить элемент по определенному индексу в массив?",
                                      optionA: "A. .append",
                                      optionB: "B. .insert(_:at:)",
                                      optionC: "C. .add(_:at:)",
                                      optionD: "D. .remove(_:at:)",
                                      correctAnswer: 2),
                            Questions(question: "Завершает текущую операцию, но полностью не выходит, а начинает новую. Про какой оператор идет речь?",
                                      optionA: "allthrough",
                                      optionB: "B. continue",
                                      optionC: "C. return",
                                      optionD: "D. break",
                                      correctAnswer: 2)
                        ]),
                   Rows(rows: "Функции",
                        questions:[
                            Questions(question: "Можно ли создать переменную с функциональным типом, например var foo: (Int, Int) -> Int?",
                                      optionA: "A. Да",
                                      optionB: "B. Нет",
                                      optionC: "",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Должны ли мы писать пустые круглые скобки при объявлении и вызове функции, если у нее нет входных параметров?",
                                      optionA: "A. Да",
                                      optionB: "B. Нет",
                                      optionC: "",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Можно ли опустить один или несколько параметров при вызове функции, если у них есть значения по умолчанию?",
                                      optionA: "A. Да",
                                      optionB: "B. Нет",
                                      optionC: "",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Какое ключевое слово в замыкании указывает, что дальше начинается тело замыкания?",
                                      optionA: "A. after",
                                      optionB: "B. out",
                                      optionC: "C. for",
                                      optionD: "D. in",
//                                          optionE: "E. C. var array = [String] ()",
                                      correctAnswer: 4),
                            Questions(question: "Можем ли мы присвоить значения по умолчанию для параметров функции?",
                                      optionA: "A. Только если параметр функции не closure",
                                      optionB: "B. Да",
                                      optionC: "C. Нет",
                                      optionD: "",
                                      correctAnswer: 2),
                            Questions(question: "Как должно начинаться имя функции в Swift?",
                                      optionA: "A. С маленькой буквы",
                                      optionB: "B. С цифры",
                                      optionC: "C. С заглавной буквы",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Может ли функция быть результирующим значением другой функции?",
                                      optionA: "A. Нет",
                                      optionB: "B. Да",
                                      optionC: "C. Только если функция без параметров",
                                      optionD: "",
                                      correctAnswer: 2),
                            Questions(question: "После выполнения оператора return функция завершает свою работу",
                                      optionA: "A. Нет",
                                      optionB: "B. Да",
                                      optionC: "",
                                      optionD: "",
                                      correctAnswer: 2),
                            Questions(question: "Обязательно ли указывать каждой функции входные параметры и результирующее значение?",
                                      optionA: "A. Да",
                                      optionB: "B. Только входные параметры",
                                      optionC: "C. Нет",
                                      optionD: "D. Только возвращаемое значение",
                                      correctAnswer: 3),
                            Questions(question: "Можем ли мы вызвать одну и ту же функцию с разными входными параметрами?",
                                      optionA: "A. Да",
                                      optionB: "B. Нет",
                                      optionC: "",
                                      optionD: "",
                                      correctAnswer: 1)
                        ]),
                   Rows(rows: "ООП в Swift",
                        questions:[
                            Questions(question: "Когда в подклассе объявляется метод с таким же названием, параметрами и возвращаемым значением как и в одном из его родительских классов, это:",
                                      optionA: "A. Переопределение метода (Method overriding)",
                                      optionB: "B. Затенение метода",
                                      optionC: "C. Так делать нельзя, возникнет ошибка",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Можно ли запретить наследоваться от класса и как?",
                                      optionA: "A. От любого класса всегда можно наследоваться",
                                      optionB: "B. Добавить ключевое слово final перед class",
                                      optionC: "C. Добавить модификатор доступа fileprivate перед class",
                                      optionD: "",
                                      correctAnswer: 2),
                            Questions(question: "Что такое инкапсуляция в ООП?",
                                      optionA: "A. Инкапсуляция - это сокрытие реализации класса и отделение его внутреннего представления от внешнего (интерфейса)",
                                      optionB: "B. Инкапсуляция - это сокрытие методов и свойств класса-наследника от класса-родителя",
                                      optionC: "C. Инкапсуляция - это хранение других объектов в теле класса",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Два и более методов с одинаковым названием в одном классе, но с разными аргументами называется:",
                                      optionA: "A. Перегрузка методов (method overloading)",
                                      optionB: "B. Переопределение методов (method overriding)",
                                      optionC: "C. Затенение метода",
                                      optionD: "",
//                                          optionE: "E. C. var array = [String] ()",
                                      correctAnswer: 1),
                            Questions(question: "Как называется класс, от которого наследуются?",
                                      optionA: "A. Суперкласс",
                                      optionB: "B. Подкласс",
                                      optionC: "C. Супермен",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Сокрытие информации можно также назвать как",
                                      optionA: "A. Полиморфизм",
                                      optionB: "B. Деинициализация",
                                      optionC: "C. Инкапсуляция",
                                      optionD: "D. Наследование",
                                      correctAnswer: 3),
                            Questions(question: "Должен ли суперкласс зависеть от своих наследников?",
                                      optionA: "A. Нет, нужно проектировать суперкласс так, чтобы его не пришлось модифицировать при добавлении наследников",
                                      optionB: "B. Да",
                                      optionC: "",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Каким оператором можно проверить, ссылаются ли переменные на один экземпляр?",
                                      optionA: "A. Оператор тождественности ===",
                                      optionB: "B. Оператор сравнения ==",
                                      optionC: "C. Оператор присваивания =",
                                      optionD: "D. defer",
                                      correctAnswer: 1),
                            Questions(question: "Как называется наследующий класс?",
                                      optionA: "A. Супермен",
                                      optionB: "B. Подкласс",
                                      optionC: "C. Суперкласс",
                                      optionD: "",
                                      correctAnswer: 2),
                            Questions(question: "Могут ли классы переопределять не private методы своего суперкласса?",
                                      optionA: "A. Нет",
                                      optionB: "B. Да",
                                      optionC: "",
                                      optionD: "",
                                      correctAnswer: 2)
                        ]),
                   Rows(rows: "Перечисления и структуры",
                        questions:[
                            Questions(question: "Какими ключевыми словами обозначаются классы и структуры в коде?",
                                      optionA: "A. classes и struct",
                                      optionB: "B. class и struct",
                                      optionC: "C. class и structures",
                                      optionD: "D. classes и structures",
                                      correctAnswer: 2),
                            Questions(question: "В каком стиле следует писать имена свойств и методов в Swift?",
                                      optionA: "A. lowerCamelCase",
                                      optionB: "B. На свое усмотрение",
                                      optionC: "C. UpperCamelCase",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Что из этого относится к типу значения?",
                                      optionA: "A. Структуры",
                                      optionB: "B. Структуры и классы",
                                      optionC: "C. Классы",
                                      optionD: "",
                                      correctAnswer: 1),
                            Questions(question: "Swift без употребления ключевого свойства self не поймет, что вы ссылаетесь на свойство или метод текущего экземпляра, так ли это?",
                                      optionA: "A. Нет",
                                      optionB: "B. Да",
                                      optionC: "",
                                      optionD: "",
//                                          optionE: "E. C. var array = [String] ()",
                                      correctAnswer: 2),
                            Questions(question: "Как называется экземпляр класса в Swift?",
                                      optionA: "A. Субъект",
                                      optionB: "B. Структура",
                                      optionC: "C. Объект",
                                      optionD: "D. Таргет",
                                      correctAnswer: 3),
                            Questions(question: "Экземпляры классов и структур (если имеют инициализатор без параметров) можно создать через этот синтаксис",
                                      optionA: "A. let objectName = ClassName[]",
                                      optionB: "B. let objectName: ClassName()",
                                      optionC: "C. let objectName = ClassName()",
                                      optionD: "D. let objectName = (ClassName)()",
                                      correctAnswer: 3),
                            Questions(question: "Чем отличаются методы от функций?",
                                      optionA: "A. Функции привязаны к типам",
                                      optionB: "B. Методы глобальнее функций",
                                      optionC: "C. Методы пишутся с заглавной буквы",
                                      optionD: "D. Методы связаны с типами",
                                      correctAnswer: 4),
                            Questions(question: "Какой стиль написания составных слов вы должны использовать в написании имен классов и структур?",
                                      optionA: "A. Зависит от команды",
                                      optionB: "B. UpperCamelCase",
                                      optionC: "C. lowerCamelCase",
                                      optionD: "D. Без разницы",
                                      correctAnswer: 2),
                            Questions(question: "Что относится к ссылочному типу?",
                                      optionA: "A. Структуры",
                                      optionB: "B. Классы",
                                      optionC: "C. Свойства",
                                      optionD: "",
                                      correctAnswer: 2),
                            Questions(question: "Что рациональнее использовать для хранения данных?",
                                      optionA: "A. Данные хранить нельзя",
                                      optionB: "B. Структуры",
                                      optionC: "C. Классы",
                                      optionD: "",
                                      correctAnswer: 2)
                        ])
                   ]),
                      Sections(sections: "Мое первое приложение",
                               rows: [Rows(rows: "UIKit",
                                           questions: [
                                            Questions(
                                            question: "В каком параметре хранится текущее значение UISlider?",
                                            optionA: "A. minValue",
                                            optionB: "B. parameter",
                                            optionC: "C. value",
                                            optionD: "D. currentValue",
                                            correctAnswer: 3),
                                            Questions(
                                            question: "Будут ли изменяться свойства UI элемента, если isHidden == true?",
                                            optionA: "A. Да",
                                            optionB: "B. Нет",
                                            optionC: "C. Зависит от версии IOS",
                                            optionD: "",
                                            correctAnswer: 2),
                                            Questions(
                                            question: "Какой тип у поля text класса UITextField?",
                                            optionA: "A. String",
                                            optionB: "B. String?",
                                            optionC: "C. Int",
                                            optionD: "D. Float",
                                            correctAnswer: 4),
                                           ])])
                     ])
     
}
